Vagrant.require_version ">= 1.8.2"

domain = 'localdomain'
box = "bento/ubuntu-16.04"
ram_size_mb = '16384'

Vagrant.configure(2) do |config|
  config.vm.box = box
  config.vm.synced_folder 'shared', '/vagrant'

  config.vm.provision :shell do |shell|
    shell.path = 'provision/setup-docker.sh'
  end
  config.vm.provision :shell do |shell|
    shell.path = 'provision/setup-pip.sh'
  end
  config.vm.provision :shell do |shell|
    shell.path = 'provision/setup-vault.sh'
  end

  config.vm.provider :virtualbox do | vbox |
    vbox.gui = false
    vbox.memory = ram_size_mb
  end
  config.vm.network :private_network, ip: '192.168.81.11'
  config.vm.network "forwarded_port", guest: 1443, host: 1443
  config.vm.network "forwarded_port", guest: 5432, host: 15432
  config.vm.provision :shell do |shell|
    shell.path = 'provision/setup-hostname.sh'
    shell.args = 'staging'
  end

  config.vm.provision :shell do |shell|
    shell.path = 'provision/setup-share.sh'
  end
end
