#!/usr/bin/env python3
"""Start the ebola server

Usage:
ebola-server [--root=ROOT] start
ebola-server [--root=ROOT] stop
ebola-server [--root=ROOT] configure
ebola-server [--root=ROOT] update-passwords
"""


import os
import os.path
import sys

import docopt


def set_root(root):
    root = os.path.abspath(root or os.path.dirname(sys.argv[0]))
    src = root + "/src"
    os.chdir(src)
    sys.path.insert(1, src)


def start():
    deploy.start()


def stop():
    deploy.stop()


def configure():
    s = deploy.service.Service({})
    deploy.configure(s)


def update_passwords():
    s = deploy.service.Service({})
    deploy.configure_proxy_users(s)


if __name__ == "__main__":
    args = docopt.docopt(__doc__)
    root = args["--root"]

    set_root(root)
    import deploy

    if args["start"]:
        start()
    elif args["stop"]:
        stop()
    elif args["update-passwords"]:
        update_passwords()
    elif args["configure"]:
        configure()
