#!/usr/bin/env bash
ROOT=$(dirname $(dirname $(realpath $0)))
DEST=$ROOT/.vault_token

export VAULT_ADDR='https://ebola2018.dide.ic.ac.uk:8200'
if [ "$VAULT_AUTH_GITHUB_TOKEN" = "" ]; then
    echo -n "Please provide your GitHub personal access token for the vault: "
    read -s TOKEN
    echo ""
    export VAULT_AUTH_GITHUB_TOKEN=${TOKEN}
fi
vault login -method=github -no-store -token-only > $DEST
