#!/usr/bin/env bash
set -e
if [ ! -d ebola-server ]; then
    git clone https://github.com/imperialebola2018/ebola-server
else
    git -C ebola-server pull
fi

sudo pip3 install -r ebola-server/requirements.txt

if [ ! -f /vagrant/vault_token ]; then
    echo "Please run scripts/vault-login"
fi
export VAULT_TOKEN=$(cat /vagrant/vault_token)

PATH_OUTPUTS=/vagrant/ebola-outputs
./ebola-server/scripts/prepare_orderly_volume --remove $PATH_OUTPUTS

./ebola-server/ebola-server start
